[package]
name = "rust_test_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "rust_test_lib"
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.24.0"